name: build

on:
  push:
    branches:
      - main

jobs:
  build_container:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./nginx
            repository: freecattle-nginx
          - context: .
            repository: freecattle-web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --push \
            -t $REGISTRY/${{ matrix.repository }}:$IMAGE_TAG \
            ${{ matrix.context }}
